### get all
GET http://localhost:8080/api/books/
Content-Type: application/json

### get by ID
GET http://localhost:8080/api/books/1
Content-Type: application/json


### Create
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "t8",
  "description": "bla bla bla8"
}

### Del
DELETE http://localhost:8080/api/books/53
Content-Type: application/json


###################

### get all
GET http://localhost:8080/api/authors/
Content-Type: application/json

### get by ID
GET http://localhost:8080/api/authors/1
Content-Type: application/json


### Create
POST http://localhost:8080/api/authors
Accept: application/json
Content-Type: application/json

{
  "idAuthor": 1,
  "name": "t39",
  "email": "too@mail.com"
}

### Del
DELETE http://localhost:8080/api/authors/8
Content-Type: application/json

### Add book to author
POST http://localhost:8080/api/authors/7/books/3
Content-Type: application/json
#######


